library(rOpenSearch)

osd.url <- "http://eo-virtual-archive4.esa.int/search/ASA_IM__0P/description"
response.type <- "application/rdf+xml"

osd.url <- "http://www.dpi.inpe.br/datasearch"
response.type <- "application/atom+xml"

df.params <- GetOSQueryables(osd.url, response.type)
df.params$value[df.params$type == "count"] <- 30
df.params$value[df.params$type == "time:start"] <- "2010-01-10"
df.params$value[df.params$type == "time:end"] <- "2010-01-31"
res <- Query(osd.url, response.type, df.params)
res

# opensearch.description <- osd.url
# real-life query by Ricardo Cartaxo http://www.dpi.inpe.br/datasearch/granule.json?&bbox=-53.635,-18.6228,-52.9403,-18.2058&path=&row=&band=&start=2018-04-01&end=2019-03-31&count=20&startIndex=1&dataset=S2SR
# query generated by this package    http://www.dpi.inpe.br/datastore/Repository/Archive//granule.atom?3=30&6=2010-01-31&5=2010-01-10
